---
# Playbook for Kali

## Deploy tools not in the Kali repositories
- hosts: kali
  become: true
  vars_files:
    - config.yml
  tasks:
    ### Clone projects from git repos ###
    # Various projects that are either not in Kali or are updated more frequently than Kali repos
    - name: Clone git repositories
      git:
        repo: "{{ item.repo }}"
        dest: "/home/djt/tools/ti/{{ item.name }}-ansible"
        version: "{{ item.version | default('master') }}"
        force: true
      loop: "{{ git_repos | flatten(levels=1) }}"

    - name: Clone git repositories for bug bounty
      git:
        repo: "{{ item.repo }}"
        dest: "/home/djt/tools/bb/{{ item.name }}-ansible"
        version: "{{ item.version | default('master') }}"
        force: true
      loop: "{{ git_repos_bb | flatten(levels=1) }}"

    - name: Clone my own git repositories
      git:
        repo: "{{ item.repo }}"
        dest: "/home/djt/tools/{{ item.name }}-ansible"
        version: "{{ item.version | default('master') }}"
        force: true
      loop: "{{ git_repos_own | flatten(levels=1) }}"

    ### Download golang repos
    - name: Go get modules
      shell: go install "{{ item.repo }}@latest"
      loop: "{{ go_repos" }}


    ### Sublime-Text ###
    - name: Add Sublime-text apt key
      apt_key:
        url: https://download.sublimetext.com/sublimehq-pub.gpg
        state: present

    - name : Add Sublime-text repository
      apt_repository:
        repo: deb https://download.sublimetext.com/ apt/stable/
        state: present
        filename: sublimetext
        mode: 640

    - name: Install Sublime-text packages
      apt:
        pkg:
          - sublime-text
          - sublime-merge
        state: present

    ### Typora ###
    - name: Add Typora apt key
      apt_key:
        url: https://typora.io/linux/public-key.asc
        state: present

    - name : Add Typora repository
      apt_repository:
        repo: deb https://typora.io/linux ./
        state: present
        filename: typora
        mode: 640

    - name: Install Typora package
      apt:
        name: typora
        state: present

    ### CyberChef ###
    - name: Creates cyberchef directory
      file:
        dest: /var/www/html/cyberchef/
        state: directory
        owner: root
        group: root
        mode: 655

    - name: Download and unarchive CyberChef
      unarchive:
        src: https://github.com/gchq/CyberChef/releases/download/v9.28.0/CyberChef_v9.28.0.zip
        dest: /var/www/html/cyberchef/
        remote_src: yes

    - name: Create a symbolic link - CyberChef
      file:
        src: /var/www/html/cyberchef/CyberChef_v9.28.0.html
        dest: /var/www/html/cyberchef.htm
        owner: root
        group: root
        state: link
